# Generated by Django 5.0.6 on 2024-06-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouriteword',
            options={},
        ),
    ]
