# Generated by Django 5.0.6 on 2024-06-08 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_app', '0003_alter_favouriteword_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouriteword',
            options={'permissions': [('can_add_favourite_word', 'Can add a favourite word'), ('can_remove_favourite_word', 'Can remove a favourite word')]},
        ),
    ]
