# Generated by Django 5.0.6 on 2024-06-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words_app', '0004_alter_favouriteword_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favouriteword',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='favouriteword',
            unique_together=set(),
        ),
    ]
